- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions > 50"
- label: "PR submitted by:"
  message: "$payload.pull_request.user.login"
  color: "blue"
- label: "Size"
  message: "$additions"
  color: "orange"
- imageUrl: "https://gitlab.cern.ch/rest-for-physics/rawlib/badges/$branchName/pipeline.svg"
  url: "https://gitlab.cern.ch/rest-for-physics/rawlib/-/commits/$branchName"
