#image: lobis/root-geant4-garfieldpp:cxx14_ROOTv6-22-08_Geant4v10.4.3
image: lobis/root-geant4-garfieldpp:cxx14_ROOTv6-25-01_Geant4v10.4.3

stages:
  - pre-build
  - build
  - loadRESTLibs
  - process
  - binaryData

before_script:
    - export USER="raw"
    - pwd
    - echo $CI_SERVER_HOST
    - echo $CRONJOB
    - export HOME=${CI_PROJECT_DIR}/install/
    - if [ -d $HOME/.rest ]; then rm -Rf $HOME/.rest; fi
    - if [ -f "/opt/root/install/bin/thisroot.sh" ]; then source /opt/root/install/bin/thisroot.sh; fi
    - root-config --version
    - if [ -f "/opt/geant4/install/bin/geant4.sh" ]; then source /opt/geant4/install/bin/geant4.sh; fi
    - geant4-config --version
    - if [ -d "/opt/garfieldpp/install" ]; then export GARFIELD_HOME=/opt/garfieldpp/install; fi
    - if [ -d "/opt/garfieldpp/install" ]; then export HEED_DATABASE=$GARFIELD_HOME/Heed/heed++/database; fi
    - if [ -d "/opt/garfieldpp/install" ]; then export LD_LIBRARY_PATH=$GARFIELD_HOME/lib:$LD_LIBRARY_PATH; fi
    - ls $GARFIELD_HOME
    - python3 --version
    - apt update && apt install -y wget

clang-format:
    stage: pre-build
    script:
        - echo "**$CRONJOB**"
        - echo "**$CI_SERVER_HOST**"
        - cd ${CI_PROJECT_DIR}/pipeline/clang-format/
        - ./clangformattest.sh
          # We execute only at a schedulled pipeline that defines CRONJOB variable
    only:
        variables:
            - $CRONJOB

validateLibrary:
    stage: pre-build
    script:
        - python3 pipeline/validateLibrary.py .
    except:
        variables:
            - $CRONJOB == "YES"

build:
  type: build
  script:
    - echo "**${CI_PROJECT_DIR}**"
    - rm -rf ${CI_PROJECT_DIR}/install
    - git clone --single-branch --branch development https://github.com/rest-for-physics/framework.git framework
    - cd framework
    - git submodule init source/libraries/raw
    - git submodule update source/libraries/raw
    - cd source/libraries/raw/
    - git checkout ${CI_COMMIT_BRANCH}
    - cd ../../../
    - mkdir build
    - cd build
    - cmake ../ -DREST_WELCOME=ON -DRESTLIB_RAW=ON -DINSTALL_PREFIX=${CI_PROJECT_DIR}/install
    - make install -j2
  except:
    variables:
      - $CRONJOB
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install
      - ${CI_PROJECT_DIR}/framework
      - ${CI_PROJECT_DIR}/framework/build
    expire_in: 1 day

loadRESTLibs:
  type: loadRESTLibs
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - restRoot -b -q
  except:
    variables:
      - $CRONJOB

addSignalNoise: 
  type: process
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/processes/
    - ./addNoise.py
  except:
      variables:
        - $CRONJOB

dreamData:
  type: binaryData
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/binaryData/dream
    - restManager --c dream.rml --f dummyDreamData.fdf
    - restRoot -b -q dream.C
